--[[                                                                           ]]--
--[[  Automatically generated code (do not edit)                               ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '12',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['POWER2'] = {
            ['rectangle'] = RECTANGLE( 44.5, 16.5, 46.5, 18.5 ),
        },
        ['POWER1'] = {
            ['rectangle'] = RECTANGLE( 44.5, 18.5, 46.5, 20.5 ),
        },
        ['POWER3'] = {
            ['rectangle'] = RECTANGLE( 44.5, 14.5, 46.5, 16.5 ),
        },
        ['FACTORY'] = {
            ['rectangle'] = RECTANGLE( 34.5, 10.5, 44.5, 20.5 ),
        },
        ['TUT_PAN'] = {
            ['rectangle'] = RECTANGLE( 30.5, 10.5, 50.5, 30.5 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Combat Zone 51'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 53.5, 18.21, 228.5 ),
                },
                ['Mass 38'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 40.5, 18.22, 9.5 ),
                },
                ['Rally Point 28'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 216.5, 18.23, 48.5 ),
                },
                ['cam_part_1'] = {
                    ['zoom'] = FLOAT( 0.000000 ),
                    ['canSetCamera'] = BOOLEAN( true ),
                    ['canSyncCamera'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff808000' ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['type'] = STRING( 'Camera Info' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Camera_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 40.5, 18.2188, 21.5 ),
                },
                ['Protected Experimental Construction 23'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 241.5, 18.2, 243.5 ),
                },
                ['Enemy'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 233.5, 18.22, 35.5 ),
                },
                ['Mass 40'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 167.5, 18.09, 246.5 ),
                },
                ['Defensive Point 81'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 96.5, 17.99, 10.5 ),
                },
                ['Combat Zone 42'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 133.5, 9.21, 124.5 ),
                },
                ['Defensive Point 21'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 78.5, 18.13, 203.5 ),
                },
                ['Defensive Point 80'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 79.5, 18.19, 54.5 ),
                },
                ['Mass 50'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 95.5, 18.16, 37.5 ),
                },
                ['Defensive Point 30'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 49.5, 18.18, 247.5 ),
                },
                ['Naval Area 53'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 82.5, 16.34, 82.5 ),
                },
                ['Combat Zone 64'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 201.5, 18.2, 32.5 ),
                },
                ['Naval Area 63'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 152.5, 16.32, 240.5 ),
                },
                ['Mass 41'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 233.5, 18.2, 23.5 ),
                },
                ['Island 26'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 36.5, 18.24, 202.5 ),
                },
                ['Combat Zone 6'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 236.5, 18.24, 209.5 ),
                },
                ['Defensive Point 33'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 9.5, 18.19, 166.5 ),
                },
                ['Island 9'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 206.5, 18.23, 218.5 ),
                },
                ['Naval Area 48'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 107.5, 15.67, 10.5 ),
                },
                ['Combat Zone 12'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 230.5, 18.22, 72.5 ),
                },
                ['Rally Point 31'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 188.5, 18.1895, 206.5 ),
                },
                ['Mass 65'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 207.5, 18.12, 179.5 ),
                },
                ['Naval Area 76'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 15.5, 16.71, 78.5 ),
                },
                ['Combat Zone 29'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 79.5, 18.23, 24.5 ),
                },
                ['Combat Zone 56'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 34.5, 18.21, 54.5 ),
                },
                ['Mass 7'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 39.5, 18.23, 29.5 ),
                },
                ['Defensive Point 1'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 206.5, 17.96, 8.5 ),
                },
                ['Defensive Point 32'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 56.5, 18.16, 170.5 ),
                },
                ['Naval Area 2'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 242.5, 16.66, 176.5 ),
                },
                ['Mass 36'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 23.5, 18.22, 224.5 ),
                },
                ['Naval Area 49'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 178.5, 16.67, 11.5 ),
                },
                ['Defensive Point 15'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 162.5, 17.8, 245.5 ),
                },
                ['Defensive Point 71'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 205.5, 18.08, 176.5 ),
                },
                ['Mass 3'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 74.5, 18.14, 204.5 ),
                },
                ['Mass 45'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 213.5, 18.22, 218.5 ),
                },
                ['Naval Area 55'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 235.5, 16.66, 105.5 ),
                },
                ['JJ_Base_Marker'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 208.5, 18.2266, 230.5 ),
                },
                ['Island 54'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 228.5, 18.22, 41.5 ),
                },
                ['Mass 79'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 23.5, 18.22, 203.5 ),
                },
                ['Mass 43'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 49.5, 18.02, 73.5 ),
                },
                ['Mass 22'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 44.5, 18.11, 160.5 ),
                },
                ['JJ'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 214.5, 18.22, 230.5 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 164.5, 18.07, 206.5 ),
                },
                ['Protected Experimental Construction 72'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 244.5, 18.2, 13.5 ),
                },
                ['Mass 62'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 188.5, 18.16, 40.5 ),
                },
                ['Protected Experimental Construction 59'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 11.5, 18.21, 239.5 ),
                },
                ['Mass 4'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 233.5, 18.21, 45.5 ),
                },
                ['Defensive Point 34'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 236.5, 18.12, 91.5 ),
                },
                ['Defensive Point 78'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 199.5, 18.08, 83.5 ),
                },
                ['Combat Zone 35'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 27.5, 18.23, 171.5 ),
                },
                ['Mass 67'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 202.5, 18.22, 231.5 ),
                },
                ['Mass 73'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 243.5, 18.22, 35.5 ),
                },
                ['Mass 52'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 215.5, 18.08, 93.5 ),
                },
                ['Defensive Point 39'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 8.5, 18.09, 47.5 ),
                },
                ['Naval Area 17'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 171.5, 15.63, 83.5 ),
                },
                ['Mass 74'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 32.5, 18.23, 213.5 ),
                },
                ['Naval Area 68'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 24.5, 15.23, 144.5 ),
                },
                ['Defensive Point 47'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 179.5, 18.07, 41.5 ),
                },
                ['Mass 77'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 92.5, 18.16, 9.5 ),
                },
                ['Mass 69'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 51.5, 18.23, 21.5 ),
                },
                ['Rally Point 19'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 39.5, 18.26, 198.5 ),
                },
                ['Combat Zone 5'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff800000' ),
                    ['type'] = STRING( 'Combat Zone' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 178.5, 18.21, 232.5 ),
                },
                ['Defensive Point 61'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 170.5, 18.16, 198.5 ),
                },
                ['Mass 27'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 213.5, 18.22, 241.5 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 225.5, 18.22, 230.5 ),
                },
                ['Naval Area 8'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 174.5, 16.53, 173.5 ),
                },
                ['Mass 70'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 246.5, 18.05, 91.5 ),
                },
                ['Mass 18'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 11.5, 18.09, 162.5 ),
                },
                ['Naval Area 16'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 84.5, 16.3, 244.5 ),
                },
                ['Mass 25'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 13.5, 18.22, 214.5 ),
                },
                ['Naval Area 14'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000FF' ),
                    ['type'] = STRING( 'Naval Area' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 82.5, 16.34, 172.5 ),
                },
                ['Mass 60'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 27.5, 18.22, 19.5 ),
                },
                ['Player'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 40.5, 18.23, 20.5 ),
                },
                ['Mass 44'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['editorIcon'] = STRING( '/textures/editor/marker_mass.bmp' ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['resource'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Mass_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 221.5, 18.22, 35.5 ),
                },
                ['Defensive Point 75'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 45.5, 17.98, 74.5 ),
                },
                ['Defensive Point 66'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Defensive Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 244.5, 18.16, 207.5 ),
                },
                ['Protected Experimental Construction 46'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Protected Experimental Construction' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Expansion_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 18.5, 18.22, 11.5 ),
                },
                ['Rally Point 57'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'FF808000' ),
                    ['type'] = STRING( 'Rally Point' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Defensive_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 53.5, 18.24, 35.5 ),
                },
                ['Island 20'] = {
                    ['hint'] = BOOLEAN( true ),
                    ['color'] = STRING( 'ff0000AA' ),
                    ['type'] = STRING( 'Island' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, -0, 0 ),
                    ['position'] = VECTOR3( 46.5, 18.23, 26.5 ),
                },
            },
        },
    },
    Chains = {
    },
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    next_army_id = '12',
    next_group_id = '6',
    next_unit_id = '113',
    Armies = 
    {
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Player'] =  
        {
            personality = '',
            plans = '',
            color = 2,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['JJ'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Commander_Group'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['Commander'] = {
                                type = 'uel0001',
                                orders = '',
                                platoon = '',
                                Position = { 40.500000, 18.218750, 21.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['Enemy'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Enemy_Group'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['Enemy'] = {
                                type = 'uel0001',
                                orders = '',
                                platoon = '',
                                Position = { 233.500000, 18.218750, 33.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['JJ'] =  
        {
            personality = '',
            plans = '',
            color = 1,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['Player'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['Ally_Group'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['Ally'] = {
                                type = 'uel0001',
                                orders = '',
                                platoon = '',
                                Position = { 214.500000, 18.218750, 228.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                    ['Buildings'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_63'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 186.500000, 18.193359, 189.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Ext_2'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 213.500000, 18.218750, 241.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_40'] = {
                                type = 'ueb2104',
                                orders = '',
                                platoon = '',
                                Position = { 187.500000, 18.195313, 191.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_24'] = {
                                type = 'ueb0101',
                                orders = '',
                                platoon = '',
                                Position = { 220.500000, 18.218750, 235.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_59'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 189.500000, 18.195313, 191.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_77'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 176.500000, 18.181641, 199.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_88'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 176.500000, 18.179688, 202.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Power_4'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 213.500000, 18.218750, 220.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_30'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 215.500000, 18.218750, 236.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_42'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 186.500000, 18.193359, 191.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Ext_5'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 167.500000, 18.097656, 246.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_58'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 189.500000, 18.195313, 190.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Ext_7'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 207.500000, 18.126953, 179.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_45'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 187.500000, 18.195313, 190.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_51'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 185.500000, 18.187500, 194.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_64'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 184.500000, 18.189453, 191.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_20'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 225.500000, 18.218750, 232.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_83'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 174.500000, 18.177734, 200.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_39'] = {
                                type = 'ueb2104',
                                orders = '',
                                platoon = '',
                                Position = { 186.500000, 18.189453, 192.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_31'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 215.500000, 18.218750, 238.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_93'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 179.500000, 18.187500, 198.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_54'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 187.500000, 18.193359, 192.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_98'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 176.500000, 18.181641, 197.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Land_1'] = {
                                type = 'ueb0101',
                                orders = '',
                                platoon = '',
                                Position = { 208.500000, 18.220703, 223.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_48'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 184.500000, 18.187500, 192.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_26'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 213.500000, 18.218750, 243.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_76'] = {
                                type = 'ueb2104',
                                orders = '',
                                platoon = '',
                                Position = { 178.500000, 18.187500, 198.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_89'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 177.500000, 18.179688, 200.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_43'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 185.500000, 18.187500, 192.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_23'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 225.500000, 18.218750, 238.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_78'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 175.500000, 18.179688, 200.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_61'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 189.500000, 18.195313, 189.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_49'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 184.500000, 18.187500, 193.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_44'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 185.500000, 18.191406, 191.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_41'] = {
                                type = 'ueb2104',
                                orders = '',
                                platoon = '',
                                Position = { 188.500000, 18.195313, 190.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_62'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 187.500000, 18.195313, 189.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_75'] = {
                                type = 'ueb2104',
                                orders = '',
                                platoon = '',
                                Position = { 177.500000, 18.183594, 199.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Power_3'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 213.500000, 18.224609, 222.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_99'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 174.500000, 18.177734, 199.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_74'] = {
                                type = 'ueb2104',
                                orders = '',
                                platoon = '',
                                Position = { 176.500000, 18.179688, 200.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_81'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 176.500000, 18.183594, 198.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_97'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 177.500000, 18.185547, 197.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_96'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 179.500000, 18.187500, 197.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_95'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 178.500000, 18.187500, 197.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_94'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 179.500000, 18.187500, 199.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_92'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 178.500000, 18.181641, 200.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_91'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 178.500000, 18.185547, 199.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_55'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 187.500000, 18.191406, 193.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_33'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 215.500000, 18.218750, 232.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_29'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 213.500000, 18.218750, 247.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_69'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 246.500000, 18.195313, 234.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_90'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 177.500000, 18.179688, 201.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_87'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 176.500000, 18.179688, 201.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_86'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 175.500000, 18.179688, 202.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_85'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 174.500000, 18.175781, 202.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Ext_6'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 164.500000, 18.085938, 206.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Ext_4'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 213.500000, 18.218750, 218.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_80'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 177.500000, 18.187500, 198.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_82'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 175.500000, 18.179688, 198.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_52'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 186.500000, 18.187500, 193.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_84'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 174.500000, 18.177734, 201.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_79'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 175.500000, 18.179688, 199.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_71'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 246.500000, 18.187500, 246.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_57'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 188.500000, 18.195313, 192.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_37'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 211.500000, 18.218750, 218.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_70'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 246.500000, 18.187500, 240.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_68'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 252.500000, 18.187500, 234.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_53'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 186.500000, 18.187500, 194.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_73'] = {
                                type = 'ueb2104',
                                orders = '',
                                platoon = '',
                                Position = { 175.500000, 18.179688, 201.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_21'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 225.500000, 18.218750, 234.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_50'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 184.500000, 18.187500, 194.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Power_1'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 213.500000, 18.220703, 226.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_47'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 185.500000, 18.193359, 190.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_56'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 188.500000, 18.195313, 191.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Ext_1'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 225.500000, 18.218750, 230.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_67'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 252.500000, 18.187500, 240.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_34'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 215.500000, 18.226563, 234.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_22'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 225.500000, 18.218750, 236.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_66'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 252.500000, 18.179688, 246.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_65'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 252.500000, 18.169922, 252.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_38'] = {
                                type = 'ueb2104',
                                orders = '',
                                platoon = '',
                                Position = { 185.500000, 18.187500, 193.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_28'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 213.500000, 18.218750, 245.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_60'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 188.500000, 18.195313, 189.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Power_2'] = {
                                type = 'ueb1101',
                                orders = '',
                                platoon = '',
                                Position = { 213.500000, 18.224609, 224.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_46'] = {
                                type = 'ueb5101',
                                orders = '',
                                platoon = '',
                                Position = { 186.500000, 18.195313, 190.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['Ext_3'] = {
                                type = 'ueb1103',
                                orders = '',
                                platoon = '',
                                Position = { 202.500000, 18.218750, 231.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_25'] = {
                                type = 'ueb0102',
                                orders = '',
                                platoon = '',
                                Position = { 208.500000, 18.218750, 244.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_72'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 246.500000, 18.193359, 252.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_107'] = {
                                type = 'ueb0301',
                                orders = '',
                                platoon = '',
                                Position = { 230.500000, 18.218750, 235.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_108'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 181.500000, 18.183594, 203.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_109'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 192.500000, 18.195313, 194.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_110'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 206.500000, 18.175781, 187.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_111'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 224.500000, 18.177734, 190.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                            ['UNIT_112'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 232.500000, 18.173828, 196.500000 },
                                Orientation = { 0.000000, 0.000000, 0.000000 },
                            },
                        },
                    },
                    ['Units'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_9'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  Army                                                                     ]]--
        --[[                                                                           ]]--
        ['ARMY_10'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}
