version = 3
ScenarioInfo = {
    name = 'Seraphim Nuke Mission',
    description = 'High command is preparing an attack on Fort Clarke.  We are launching an attack against the heavily defended human city of New Sanctuary to draw out and destroy Fort Clarke defenders. For this mission, you are being granted use of the Yolona Oss experimental nuke launcher.  You will use it to crush all Coalition forces and destroy New Sanctuary.',
    type = 'campaign_coop',
    starts = true,
    preview = '',
    size = {2048, 2048},
    map = '/maps/SeraNukeMission/SeraNukeMission.scmap',
    save = '/maps/SeraNukeMission/SeraNukeMission_save.lua',
    script = '/maps/SeraNukeMission/SeraNukeMission_script.lua',
    norushradius = 0.000000,
    norushoffsetX_Player = 0.000000,
    norushoffsetY_Player = 0.000000,
    norushoffsetX_Seraphim = 0.000000,
    norushoffsetY_Seraphim = 0.000000,
    norushoffsetX_Order = 0.000000,
    norushoffsetY_Order = 0.000000,
    norushoffsetX_UEF = 0.000000,
    norushoffsetY_UEF = 0.000000,
    norushoffsetX_Aeon = 0.000000,
    norushoffsetY_Aeon = 0.000000,
    norushoffsetX_Cybran = 0.000000,
    norushoffsetY_Cybran = 0.000000,
    norushoffsetX_Civilians = 0.000000,
    norushoffsetY_Civilians = 0.000000,
    norushoffsetX_Coop1 = 0.000000,
    norushoffsetY_Coop1 = 0.000000,
    norushoffsetX_Coop2 = 0.000000,
    norushoffsetY_Coop2 = 0.000000,
    norushoffsetX_Coop3 = 0.000000,
    norushoffsetY_Coop3 = 0.000000,
    Configurations = {
        ['standard'] = {
            teams = {
                { name = 'FFA', armies = {'Player','Seraphim','Order','UEF','Aeon','Cybran','Civilians','Coop1','Coop2','Coop3',} },
            },
            customprops = {
            },
        },
    }}
